/* =====================================================
   SECTION 1 — CUSTOMER ANALYSIS
   Purpose: understand customer behavior & value
   ===================================================== */


/* -----------------------------------------------------
   Query 1 — Orders per customer
   Goal: measure how active each customer is
   ----------------------------------------------------- */

SELECT 
    customer_id,              -- unique customer identifier
    COUNT(*) AS total_orders  -- total orders placed
FROM orders
GROUP BY customer_id
ORDER BY total_orders DESC;


/* -----------------------------------------------------
   Query 2 — Revenue per customer
   Goal: measure total spending per customer
   ----------------------------------------------------- */

SELECT 
    o.customer_id,  -- customer linked via orders
	-- total money spent = item price + shipping
    SUM(oi.price + oi.freight_value) AS total_revenue
FROM orders o
-- join order items to access price
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.customer_id
ORDER BY total_revenue DESC;


/* -----------------------------------------------------
   Query 3 — Top 10 customers by spending
   Goal: identify highest value customers
   ----------------------------------------------------- */

SELECT 
    o.customer_id,
    SUM(oi.price + oi.freight_value) AS total_spent
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.customer_id
ORDER BY total_spent DESC
LIMIT 10;  -- top 10 only


/* -----------------------------------------------------
   Query 4 — Repeat customers
   Goal: find customers with multiple purchases
   ----------------------------------------------------- */

SELECT 
    customer_id,
    COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 1;  -- only repeat buyers


/* -----------------------------------------------------
   Query 5 — Customers above average spending
   Goal: compare customer vs platform average
   (subquery logic)
   ----------------------------------------------------- */

SELECT 
    customer_id,
    total_spent
FROM
(
    -- inner query: calculate spending per customer
    SELECT 
        o.customer_id,
        SUM(oi.price + oi.freight_value) AS total_spent
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
) t
WHERE total_spent >
(
    -- subquery: average customer spending
    SELECT AVG(price + freight_value)
    FROM order_items
);


/* -----------------------------------------------------
   Query 6 — Average order value per customer
   Goal: understand spending consistency
   ----------------------------------------------------- */

SELECT 
    o.customer_id,
	-- average order size
    AVG(oi.price + oi.freight_value) AS avg_order_value
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.customer_id
ORDER BY avg_order_value DESC;


/* -----------------------------------------------------
   Query 7 — Customers per city
   Goal: geographic customer distribution
   ----------------------------------------------------- */

SELECT 
    customer_city,
    COUNT(*) AS total_customers
FROM customers
GROUP BY customer_city
ORDER BY total_customers DESC;


/* -----------------------------------------------------
   Query 8 — Customers per state
   Goal: regional customer concentration
   ----------------------------------------------------- */

SELECT 
    customer_state,
    COUNT(*) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC;


/* -----------------------------------------------------
   Query 9 — Customers who gave reviews
   Goal: measure engagement level
   ----------------------------------------------------- */

SELECT DISTINCT
    o.customer_id  -- unique reviewing customers
FROM reviews r
JOIN orders o
    ON r.order_id = o.order_id;


/* -----------------------------------------------------
   Query 10 — Customers with above average rating
   Goal: identify highly satisfied customers
   (subquery comparison)
   ----------------------------------------------------- */

SELECT 
    o.customer_id,
    AVG(r.review_score) AS avg_rating
FROM reviews r
JOIN orders o
    ON r.order_id = o.order_id
GROUP BY o.customer_id
HAVING avg_rating >
(
    -- average platform rating
    SELECT AVG(review_score)
    FROM reviews
);

/* =====================================================
   SECTION 2 — REVENUE ANALYSIS
   Purpose: understand financial performance & trends
   ===================================================== */


/* -----------------------------------------------------
   Query 11 — Total platform revenue
   Goal: calculate total money generated by marketplace
   ----------------------------------------------------- */
   
SELECT 
    -- total revenue = item price + shipping
    SUM(oi.price + oi.freight_value) AS total_platform_revenue
FROM order_items oi;


/* -----------------------------------------------------
   Query 12 — Average order value
   Goal: understand typical order spending
  ------------------------------------------------------ */

SELECT 
    -- average value per order
    AVG(order_total) AS avg_order_value
FROM
(
    -- inner query calculates total per order
    SELECT 
        oi.order_id,
        SUM(oi.price + oi.freight_value) AS order_total
    FROM order_items oi
    GROUP BY oi.order_id
) t;  -- temporary table of order totals



/* -----------------------------------------------------
   Query 13 — Highest single order
   Goal: find the biggest purchase ever made
   ----------------------------------------------------- */

SELECT 
    oi.order_id,
    -- total order value
    SUM(oi.price + oi.freight_value) AS order_value
FROM order_items oi
GROUP BY oi.order_id
ORDER BY order_value DESC   -- highest first
LIMIT 1;                    -- only top order


/* -----------------------------------------------------
   Query 14 — Top cities by revenue
   Goal: identify revenue-driving locations
   ----------------------------------------------------- */

SELECT 
    c.customer_city,  -- city name
    -- revenue generated by city
    SUM(oi.price + oi.freight_value) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_city
ORDER BY total_revenue DESC;


/* -----------------------------------------------------
   Query 15 — Top states by revenue
   Goal: geographic revenue comparison
  ------------------------------------------------------ */

SELECT 
    c.customer_state,  -- state code
    -- revenue per state
    SUM(oi.price + oi.freight_value) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC;


/* -----------------------------------------------------
   Query 16 — Monthly revenue trend
   Goal: analyze revenue growth over time
  ------------------------------------------------------ */

SELECT 
    -- extract year-month from purchase timestamp
    DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
	-- monthly revenue
    SUM(oi.price + oi.freight_value) AS monthly_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;


/* -----------------------------------------------------
   Query 17 — Orders above average value
   Goal: identify high-value transactions
   (subquery comparison)
   ----------------------------------------------------- */

SELECT 
    order_id,
    order_total
FROM
(
    -- calculate total per order
    SELECT 
        oi.order_id,
        SUM(oi.price + oi.freight_value) AS order_total
    FROM order_items oi
    GROUP BY oi.order_id
) t
WHERE order_total >
(
    -- average order value
    SELECT AVG(price + freight_value)
    FROM order_items
);


/* -----------------------------------------------------
   Query 18 — Revenue by payment type
   Goal: understand payment behavior impact
   ----------------------------------------------------- */

SELECT 
    p.payment_type,  -- credit card, boleto, etc.
	-- total revenue by payment method
    SUM(p.payment_value) AS total_revenue
FROM payments p
GROUP BY p.payment_type
ORDER BY total_revenue DESC;


/* -----------------------------------------------------
   Query 19 — Top product categories by revenue
   Goal: identify best-performing product segments
   ----------------------------------------------------- */

SELECT 
    pr.product_category_name,  -- category label
	-- revenue generated by category
    SUM(oi.price + oi.freight_value) AS total_revenue
FROM order_items oi
JOIN products pr
    ON oi.product_id = pr.product_id
GROUP BY pr.product_category_name
ORDER BY total_revenue DESC;


/* -----------------------------------------------------
   Query 20 — Revenue from reviewed orders
   Goal: compare revenue linked to customer feedback
   ----------------------------------------------------- */

SELECT 
    SUM(oi.price + oi.freight_value) AS reviewed_revenue
FROM reviews r
JOIN orders o
    ON r.order_id = o.order_id
JOIN order_items oi
    ON o.order_id = oi.order_id;

/* =====================================================
   SECTION 3 — LOGISTICS ANALYSIS
   Purpose: evaluate delivery efficiency & operations
   ===================================================== */


/* -----------------------------------------------------
   Query 21 — Average delivery time
   Goal: measure platform-wide delivery efficiency
   ----------------------------------------------------- */

SELECT
    -- average days from purchase to delivery
    AVG(DATEDIFF(
        o.order_delivered_customer_date,
        o.order_purchase_timestamp
    )) AS avg_delivery_days
FROM orders o
-- ignore orders not delivered yet
WHERE o.order_delivered_customer_date IS NOT NULL;


/* -----------------------------------------------------
   Query 22 — Delivery time per city
   Goal: compare logistics performance by location
   ----------------------------------------------------- */

SELECT
    c.customer_city,  -- customer city

    -- average delivery days per city
    AVG(DATEDIFF(
        o.order_delivered_customer_date,
        o.order_purchase_timestamp
    )) AS avg_delivery_days
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_city
-- slowest cities first
ORDER BY avg_delivery_days DESC;


/* -----------------------------------------------------
   Query 23 — Fastest delivery city
   Goal: identify best-performing logistics location
   ----------------------------------------------------- */

SELECT
    c.customer_city,
    AVG(DATEDIFF(
        o.order_delivered_customer_date,
        o.order_purchase_timestamp
    )) AS avg_delivery_days
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_city
-- fastest cities first
ORDER BY avg_delivery_days ASC
LIMIT 1;


/* -----------------------------------------------------
   Query 24 — Slowest delivery city
   Goal: detect logistics bottlenecks
   ----------------------------------------------------- */

SELECT
    c.customer_city,
    AVG(DATEDIFF(
        o.order_delivered_customer_date,
        o.order_purchase_timestamp
    )) AS avg_delivery_days
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_city
-- slowest city
ORDER BY avg_delivery_days DESC
LIMIT 1;


/* -----------------------------------------------------
   Query 25 — Orders without delivery date
   Goal: detect incomplete or failed deliveries
   ----------------------------------------------------- */

SELECT
    COUNT(*) AS undelivered_orders
FROM orders
-- delivery timestamp missing
WHERE order_delivered_customer_date IS NULL;


/* -----------------------------------------------------
   Query 26 — Late deliveries
   Goal: count orders delivered after estimated date
   ----------------------------------------------------- */

SELECT
    COUNT(*) AS late_deliveries
FROM orders
-- delivered after promised date
WHERE order_delivered_customer_date > order_estimated_delivery_date;


/* -----------------------------------------------------
   Query 27 — Average freight cost
   Goal: measure typical shipping expense
   ----------------------------------------------------- */

SELECT
    AVG(freight_value) AS avg_freight_cost
FROM order_items;


/* -----------------------------------------------------
   Query 28 — Freight cost per seller
   Goal: compare shipping burden by seller
   ----------------------------------------------------- */

SELECT
    seller_id,
    -- average freight per seller
    AVG(freight_value) AS avg_freight
FROM order_items
GROUP BY seller_id
ORDER BY avg_freight DESC;


/* -----------------------------------------------------
   Query 29 — Top 5 cities with longest delivery time
   Goal: highlight worst-performing logistics regions
   ----------------------------------------------------- */

SELECT
    c.customer_city,
    AVG(DATEDIFF(
        o.order_delivered_customer_date,
        o.order_purchase_timestamp
    )) AS avg_delivery_days
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_city
ORDER BY avg_delivery_days DESC
LIMIT 5;


/* -----------------------------------------------------
   Query 30 — Delivery vs review score
   Goal: compare delivery speed with customer satisfaction
   ----------------------------------------------------- */

SELECT
    r.review_score,
    AVG(DATEDIFF(
        o.order_delivered_customer_date,
        o.order_purchase_timestamp
    )) AS avg_delivery_days
FROM reviews r
JOIN orders o
    ON r.order_id = o.order_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY r.review_score
ORDER BY r.review_score DESC;


/* ============================================================
   Section 4 — Seller Analysis
   Purpose: marketplace performance & seller contribution
============================================================ */


/* ------------------------------------------------------------
   Query 31 — Products sold per seller
   Goal: measure seller activity level
------------------------------------------------------------ */

SELECT
    oi.seller_id,  -- seller identifier
    -- total items sold by seller
    COUNT(*) AS total_products_sold
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY total_products_sold DESC;


/* ------------------------------------------------------------
   Query 32 — Orders per seller
   Goal: understand seller order volume
------------------------------------------------------------ */

SELECT
    oi.seller_id,
    -- count unique orders handled
    COUNT(DISTINCT oi.order_id) AS total_orders
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY total_orders DESC;


/* ------------------------------------------------------------
   Query 33 — Revenue per seller
   Goal: evaluate seller financial performance
------------------------------------------------------------ */

SELECT
    oi.seller_id,
    -- seller revenue = item price + freight
    SUM(oi.price + oi.freight_value) AS total_revenue
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY total_revenue DESC;


/* ------------------------------------------------------------
   Query 34 — Top 10 sellers by revenue
   Goal: identify marketplace leaders
------------------------------------------------------------ */

SELECT
    oi.seller_id,
    SUM(oi.price + oi.freight_value) AS total_revenue
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY total_revenue DESC
LIMIT 10;


/* ------------------------------------------------------------
   Query 35 — Seller average order value
   Goal: measure seller pricing strength
------------------------------------------------------------ */

SELECT
    oi.seller_id,
    -- average value per item sold
    AVG(oi.price + oi.freight_value) AS avg_order_value
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY avg_order_value DESC;


/* ------------------------------------------------------------
   Query 36 — Seller average rating
   Goal: evaluate seller customer satisfaction
------------------------------------------------------------ */

SELECT
    oi.seller_id,
    -- average review score for seller
    AVG(r.review_score) AS avg_rating
FROM order_items oi
JOIN reviews r
    ON oi.order_id = r.order_id
GROUP BY oi.seller_id
ORDER BY avg_rating DESC;


/* ------------------------------------------------------------
   Query 37 — Sellers with cancellations
   Goal: detect reliability risk
------------------------------------------------------------ */

SELECT
    oi.seller_id,
    -- count cancelled orders
    COUNT(*) AS cancelled_orders
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'canceled'
GROUP BY oi.seller_id
ORDER BY cancelled_orders DESC;


/* ------------------------------------------------------------
   Query 38 — Seller contribution percentage
   Goal: measure seller share of total revenue
------------------------------------------------------------ */

SELECT
    oi.seller_id,
    SUM(oi.price + oi.freight_value) AS seller_revenue,
    -- seller share vs platform total
    ROUND(
        SUM(oi.price + oi.freight_value) /
        (SELECT SUM(price + freight_value) FROM order_items) * 100,
        2
    ) AS contribution_percent
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY contribution_percent DESC;


/* ------------------------------------------------------------
   Query 39 — Active sellers count
   Goal: measure marketplace participation
------------------------------------------------------------ */

SELECT
    COUNT(DISTINCT seller_id) AS active_sellers
FROM order_items;


/* ------------------------------------------------------------
   Query 40 — Sellers above average orders
   Goal: identify high-performing sellers
------------------------------------------------------------ */

SELECT
    seller_id,
    total_orders
FROM (
    SELECT
        seller_id,
        COUNT(DISTINCT order_id) AS total_orders
    FROM order_items
    GROUP BY seller_id
) t
WHERE total_orders >
    (
        SELECT AVG(order_count)
        FROM (
            SELECT COUNT(DISTINCT order_id) AS order_count
            FROM order_items
            GROUP BY seller_id
        ) avg_table
    )
ORDER BY total_orders DESC;


/* ============================================================
   Section 5 — Comparative Performance Analysis
   Purpose: identifying above-average performance
============================================================ */


/* ------------------------------------------------------------
   Query 41 — Customers above average spending
   Goal: detect high-value customers
------------------------------------------------------------ */

SELECT
    o.customer_id,
    SUM(oi.price + oi.freight_value) AS total_spent
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.customer_id
HAVING total_spent >
(
    SELECT AVG(price + freight_value)
    FROM order_items
)
ORDER BY total_spent DESC;


/* ------------------------------------------------------------
   Query 42 — Orders above average value
   Goal: identify large transactions
------------------------------------------------------------ */

SELECT
    oi.order_id,
    SUM(oi.price + oi.freight_value) AS order_total
FROM order_items oi
GROUP BY oi.order_id
HAVING order_total >
(
    SELECT AVG(price + freight_value)
    FROM order_items
)
ORDER BY order_total DESC;


/* ------------------------------------------------------------
   Query 43 — Sellers above average revenue
   Goal: detect high-performing sellers
------------------------------------------------------------ */

SELECT
    oi.seller_id,
    SUM(oi.price + oi.freight_value) AS seller_revenue
FROM order_items oi
GROUP BY oi.seller_id
HAVING seller_revenue >
(
    SELECT AVG(price + freight_value)
    FROM order_items
)
ORDER BY seller_revenue DESC;


/* ------------------------------------------------------------
   Query 44 — Cities above average revenue
   Goal: identify strong markets
------------------------------------------------------------ */

SELECT
    c.customer_city,
    SUM(oi.price + oi.freight_value) AS city_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_city
HAVING city_revenue >
(
    SELECT AVG(price + freight_value)
    FROM order_items
)
ORDER BY city_revenue DESC;


/* ------------------------------------------------------------
   Query 45 — High value customers with high ratings
   Goal: combine revenue and satisfaction
------------------------------------------------------------ */

SELECT
    o.customer_id,
    SUM(oi.price + oi.freight_value) AS total_spent,
    AVG(r.review_score) AS avg_rating
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN reviews r
    ON o.order_id = r.order_id
GROUP BY o.customer_id
HAVING avg_rating >= 4
ORDER BY total_spent DESC;


/* ============================================================
   Section 6 — Window Analytics
   Focus: ranking and cumulative performance metrics
============================================================ */


/* ------------------------------------------------------------
   Query 46 — Rank customers by spending
   Goal: leaderboard of top customers
------------------------------------------------------------ */

SELECT
    customer_id,
    total_spent,
	RANK() OVER (ORDER BY total_spent DESC) AS spending_rank
FROM (
    SELECT
        o.customer_id,
        SUM(oi.price + oi.freight_value) AS total_spent
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
) t;


/* ------------------------------------------------------------
   Query 47 — Rank sellers by revenue
   Goal: identify marketplace leaders
------------------------------------------------------------ */

SELECT
    seller_id,
    seller_revenue,
    RANK() OVER (ORDER BY seller_revenue DESC) AS seller_rank
FROM (
    SELECT
        seller_id,
        SUM(price + freight_value) AS seller_revenue
    FROM order_items
    GROUP BY seller_id
) t;


/* ------------------------------------------------------------
   Query 48 — Running total revenue
   Goal: cumulative revenue growth
------------------------------------------------------------ */

SELECT
    month,
    monthly_revenue,
    SUM(monthly_revenue)
        OVER (ORDER BY month) AS running_total
FROM (
    SELECT
        DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
        SUM(oi.price + oi.freight_value) AS monthly_revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY month
) t;


/* ------------------------------------------------------------
   Query 49 — Row number of customers by spending
   Goal: assign sequential rank without ties
------------------------------------------------------------ */

SELECT
    customer_id,
    total_spent,
	ROW_NUMBER() OVER (ORDER BY total_spent DESC) AS row_rank
FROM (
    SELECT
        o.customer_id,
        SUM(oi.price + oi.freight_value) AS total_spent
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
) t;


/* ============================================================
   Query 50 — Row number of orders by purchase date
   Goal: sequence customer orders over time
============================================================ */

SELECT
    order_id,
    order_purchase_timestamp,
    -- assign sequential number
    ROW_NUMBER() OVER (
        ORDER BY order_purchase_timestamp
    ) AS order_sequence
FROM orders;










